name: Update README

on:
  push:
    paths:
      - 'scripts/AnnualReport_FactSheet.md'  # Runs only when this file changes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy contents of AnnualReport_FactSheet.md to README.md
        run: cat scripts/AnnualReport_FactSheet.md > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Updated README with latest AnnualReport_FactSheet.md content"
          git push
